---
kind: pipeline
name: default

steps:
  - name: submodule
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update
      - git clean -dfx .

  - name: build
    image: plugins/hugo
    settings:
      # hugo_version: 0.69
      validate: true
      # pull: always
      # url: https://foo.com
      # config: path/to/config
      # content: path/to/content/
      # layout: path/to/layout
      # output: path/to/public
      # source: path/to/source
      # theme: path/themes/THEMENAME/

  - name: deploy
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: deploy_ssh_key
      RSYNC_USER:
        from_secret: deploy_ssh_user
      PLUGIN_HOSTS:
        from_secret: deploy_host
    settings:
      source: public/
      target:
        from_secret: deploy_dir
      delete: true
    when:
      branch:
        - master
