---
baseurl: 'https://mau.ro/'
# languageCode: en-US
title: Mauro Torrez
# Enable comments by entering your Disqus shortname
disqusShortname: ''
# Enable Google Analytics by entering your tracking code
googleAnalytics: ''

theme: mauro
permalinks:
  post: '/:year/:month/:day/:slug'

DefaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    # baseurl: https://mau.ro/
  es:
    languageName: Español
    description: Sitio web personal de Mauro Torrez
    weight: 2
    # baseurl: https://mau.ro/es/
  fr:
    languageName: Français
    description: Site web personnel de Mauro Torrez
    weight: 3
    # baseurl: https://mau.ro/fr/

params:
  avatar: profile.png
  author: Mauro Torrez
  description: Mauro Torrez's personal website
  # Custom assets can be linked with their paths relative to static/
  custom_css: []
  custom_js: []
  social:
    Github: maurete
    Email: inbox@mau.ro
#  Twitter       = "eumau"
    LinkedIn: maurotorrez
#  Stackoverflow = "username"
#  Medium        = "username"
    Telegram: maurete
  cv:
    website: https://mau.ro
    website_full: 'https://mau.ro/'
  #tel = "+44 0000 000000"
  #tel_full = "+440000000000"
  #google_maps = "https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL"
  #address = "44 Perth Street"
  #postcode = "EH3 5BL"
    city: Santa Fe
    country: Argentina

## Main Menu
# [[menu.main]]
#   name = "blog"
#   weight = 100
#   identifier = "blog"
#   url = "/blog/"
# [[menu.main]]
#   name = "projects"
#   identifier = "projects"
#   weight = 200
#   url = "/projects/"

menu:
  main:
    - name: CV
      identifier: cv
      weight: 300
      url: /cv/
